# Start from the latest golang base image
FROM golang:1.21.4
RUN apt-get update && apt-get install -y iputils-ping
WORKDIR /booking-service
COPY ./src/booking-microservice/go.mod ./src/booking-microservice/go.sum ./
RUN go mod download
COPY ./src/booking-microservice/ .
RUN go build -o main .
RUN chmod +x main
EXPOSE 5001
CMD ["./main"]
