# Start from the latest golang base image
FROM golang:1.21.4
RUN apt-get update && apt-get install -y iputils-ping
WORKDIR /product-service
COPY ./src/product-microservice/go.mod ./src/product-microservice/go.sum ./
RUN go mod download
COPY ./src/product-microservice/ .
RUN go build -o main .
RUN chmod +x main
EXPOSE 5000
CMD ["./main"]
