# Start from the latest golang base image
FROM golang:1.21.4
RUN apt-get update && apt-get install -y iputils-ping
WORKDIR /pricing-service
COPY ./src/pricing-microservice/go.mod ./src/pricing-microservice/go.sum ./
RUN go mod download
COPY ./src/pricing-microservice/ .
RUN go build -o main .
RUN chmod +x main
EXPOSE 5002
CMD ["./main"]
