# Start from the latest golang base image
FROM golang:1.21.4
RUN apt-get update && apt-get install -y iputils-ping
WORKDIR /sending-service
COPY ./src/sending-microservice/go.mod ./src/sending-microservice/go.sum ./
RUN go mod download
COPY ./src/sending-microservice/ .
RUN go build -o main .
RUN chmod +x main
EXPOSE 5003
CMD ["./main"]
